- hosts: all
  become: false
  gather_facts: false

  tasks:

  - name: Clone VM 1
    community.general.proxmox_kvm:
      api_host: proxmox
      api_user: root@pam
      api_password: "#Munchkin1"
      node: proxmox
      clone: "ubuntu-cloud"
      name: rmc-rke2-01
      newid: 5001
      state: present

  - name: Update VM 1
    community.general.proxmox_kvm:
      api_host: proxmox
      api_user: root@pam
      api_password: "#Munchkin1"
      node: proxmox
      name: rmc-rke2-01
      agent: enabled=1
      vmid: 5001
      net:
        net0: 'virtio,bridge=vmbr1'
      ipconfig:
        ipconfig0: 'ip=192.168.3.211/24,gw=192.168.3.1'
      update: true


  - name: Clone VM 2
    community.general.proxmox_kvm:
      api_host: proxmox
      api_user: root@pam
      api_password: "#Munchkin1"
      node: proxmox
      clone: "ubuntu-cloud"
      name: rmc-rke2-02
      newid: 5002
      state: present

  - name: Update VM 2
    community.general.proxmox_kvm:
      api_host: proxmox
      api_user: root@pam
      api_password: "#Munchkin1"
      node: proxmox
      name: rmc-rke2-02
      agent: enabled=1
      vmid: 5002
      net:
        net0: 'virtio,bridge=vmbr1'
      ipconfig:
        ipconfig0: 'ip=192.168.3.212/24,gw=192.168.3.1'
      update: true


  - name: Clone VM 3
    community.general.proxmox_kvm:
      api_host: proxmox
      api_user: root@pam
      api_password: "#Munchkin1"
      node: proxmox
      clone: "ubuntu-cloud"
      name: rmc-rke2-03
      newid: 5003
      state: present

  - name: Update VM 3
    community.general.proxmox_kvm:
      api_host: proxmox
      api_user: root@pam
      api_password: "#Munchkin1"
      node: proxmox
      name: rmc-rke2-03
      agent: enabled=1
      vmid: 5003
      net:
        net0: 'virtio,bridge=vmbr1'
      ipconfig:
        ipconfig0: 'ip=192.168.3.213/24,gw=192.168.3.1'
      update: true


  - name: Clone VM 4
    community.general.proxmox_kvm:
      api_host: proxmox
      api_user: root@pam
      api_password: "#Munchkin1"
      node: proxmox
      clone: "ubuntu-cloud"
      name: rmc-rke2-04
      newid: 5004
      state: present

  - name: Update VM 4
    community.general.proxmox_kvm:
      api_host: proxmox
      api_user: root@pam
      api_password: "#Munchkin1"
      node: proxmox
      name: rmc-rke2-04
      agent: enabled=1
      vmid: 5004
      net:
        net0: 'virtio,bridge=vmbr1'
      ipconfig:
        ipconfig0: 'ip=192.168.3.214/24,gw=192.168.3.1'
      update: true


  - name: Clone VM 5
    community.general.proxmox_kvm:
      api_host: proxmox
      api_user: root@pam
      api_password: "#Munchkin1"
      node: proxmox
      clone: "ubuntu-cloud"
      name: rmc-rke2-05
      newid: 5005
      state: present

  - name: Update VM 5
    community.general.proxmox_kvm:
      api_host: proxmox
      api_user: root@pam
      api_password: "#Munchkin1"
      node: proxmox
      name: rmc-rke2-05
      agent: enabled=1
      vmid: 5005
      net:
        net0: 'virtio,bridge=vmbr1'
      ipconfig:
        ipconfig0: 'ip=192.168.3.215/24,gw=192.168.3.1'
      update: true

