- hosts: all
  become: false
  gather_facts: false

  tasks:

  - name: Clone VM 1
    community.general.proxmox_kvm:
      api_host: proxmox
      api_user: root@pam
      api_password: "#Munchkin1"
      node: proxmox
      clone: "ubuntu-cloud"
      name: rmc-rke2-01
      newid: 4001

  - name: Clone VM 2
    community.general.proxmox_kvm:
      api_host: proxmox
      api_user: root@pam
      api_password: "#Munchkin1"
      node: proxmox
      clone: "ubuntu-cloud"
      name: rmc-rke2-02
      newid: 4002

  - name: Clone VM 3
    community.general.proxmox_kvm:
      api_host: proxmox
      api_user: root@pam
      api_password: "#Munchkin1"
      node: proxmox
      clone: "ubuntu-cloud"
      name: rmc-rke2-03
      newid: 4003

  - name: Clone VM 4
    community.general.proxmox_kvm:
      api_host: proxmox
      api_user: root@pam
      api_password: "#Munchkin1"
      node: proxmox
      clone: "ubuntu-cloud"
      name: rmc-rke2-04
      newid: 4004

  - name: Clone VM 5
    community.general.proxmox_kvm:
      api_host: proxmox
      api_user: root@pam
      api_password: "#Munchkin1"
      node: proxmox
      clone: "ubuntu-cloud"
      name: rmc-rke2-05
      newid: 4005


  - name: SetIP 1
    ansible.builtin.shell: 'qm set 4001 --ipconfig0 ip=192.168.3.101/24,gw=192.168.3.1,ip6=dhcp'
  - name: SetIP 2
    ansible.builtin.shell: 'qm set 4002 --ipconfig0 ip=192.168.3.102/24,gw=192.168.3.1,ip6=dhcp'
  - name: SetIP 3
    ansible.builtin.shell: 'qm set 4003 --ipconfig0 ip=192.168.3.103/24,gw=192.168.3.1,ip6=dhcp'
  - name: SetIP 4
    ansible.builtin.shell: 'qm set 4004 --ipconfig0 ip=192.168.3.104/24,gw=192.168.3.1,ip6=dhcp'
  - name: SetIP 5
    ansible.builtin.shell: 'qm set 4005 --ipconfig0 ip=192.168.3.105/24,gw=192.168.3.1,ip6=dhcp'
