- hosts: all
  become: false
  gather_facts: false

  vars_prompt:
    #    - name: api_password
    #      prompt: "Enter the API password"

        #    - name: user_password
        # prompt: "Enter the user password to be used"

        #    api:
        # - name: token_secret
        # prompt: "Enter the API Token Secret"

#      token_secret: b9e5abd5-cb03-4584-a4fa-6a92d6b30c78

  vars:
    api_password: "#Munchkin1"
    user_password: "#Munchkin1"

    base_id: 4100
    base_ip: "192.168.3."
    ip_last_octet: 230
    base_name: rmc-node
    auth:
      user: "ubuntu"
      public_ssh_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM6dlqga9TQk0Y/MlWmabyteU1Q1cy4i+d+zNuX9WACs brynn@lenovo"
    api:
      host: proxmox
      user: root@pam
      token_id: ansible@pam!ansible-token
    vm_template: "ubuntu-cloud"

  tasks:

  - name: Clone-Jumphost
    vars:
      ansible_python_interpreter: /usr/bin/python3
    community.general.proxmox_kvm:
      api_host: "{{ api.host }}"
      api_user: "{{ api.user }}"
      api_password: "{{ api_password }}"
      node: "{{ api.host }}"
      clone: "{{ vm_template }}"
      name: "{{ base_name }}-jumphost"
      newid: "{{ base_id | int + 0 }}"
      state: present

  - name: Update-Jumphost
    community.general.proxmox_kvm:
      api_host: "{{ api.host }}"
      api_user: "{{ api.user }}"
      api_password: "{{ api_password }}"
      node: "{{ api.host }}"
      name: "{{ base_name }}-jumphost"
      agent: enabled=1
      vmid: "{{ base_id | int + 0 }}"
      net:
        net0: 'virtio,bridge=vmbr1'
      ipconfig:
        ipconfig0: "ip={{ base_ip }}{{ ip_last_octet | int + 0 }}/24,gw={{ base_ip }}1"
      update: true


  - name: Clone-Host1
    vars:
      ansible_python_interpreter: /usr/bin/python3
    community.general.proxmox_kvm:
      api_host: "{{ api.host }}"
      api_user: "{{ api.user }}"
      api_password: "{{ api_password }}"
      node: "{{ api.host }}"
      clone: "{{ vm_template }}"
      name: "{{ base_name }}-1"
      newid: "{{ base_id | int + 1 }}"
      state: present

  - name: Update-Host1
    community.general.proxmox_kvm:
      api_host: "{{ api.host }}"
      api_user: "{{ api.user }}"
      api_password: "{{ api_password }}"
      node: "{{ api.host }}"
      name: "{{ base_name }}-1"
      agent: enabled=1
      vmid: "{{ base_id | int + 1 }}"
      net:
        net0: 'virtio,bridge=vmbr1'
      ipconfig:
        ipconfig0: "ip={{ base_ip }}{{ ip_last_octet | int + 1 }}/24,gw={{ base_ip }}1"
      update: true
